# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Empirical cdf
#'
#' @description This function estimates an empirical cdf using the reference parameter and then 
#' evaluates the estimated empirical cdf at the points specified in the sample parameter. 
#' 
#' @param reference NumericVector containing reference points to which to fit empirical cdf
#' @param sample NumericVector containing points at which to evaluate empirical cdf
#' @return NumericVector of estimated quantiles of sample values
#' 
#' @export
#' @author Tom Willis
ecdf_cpp <- function(reference, sample) {
    .Call(`_pidProjCode_ecdf_cpp`, reference, sample)
}

#' @title Bivariate empirical cdf
#'
#' @description This function fits a bivariate ecdf to the specified pair of variables and then evaluates the ecdf at the same points.
#'
#' @details Assumes u_ref and v_ref specify pairs of points in the correct order.
#' 
#' @param u_ref NumericVector reference points in first dimension
#' @param v_ref NumericVector reference points in second dimension
#'
#' @return NumericVector of estimated quantiles of specified pairs
#' @export
#' @author Tom Willis
bivariate_ecdf_cpp <- function(u_ref, v_ref) {
    .Call(`_pidProjCode_bivariate_ecdf_cpp`, u_ref, v_ref)
}

#' @title Parallel implementation of bivariate empirical cdf
#'
#' @description This function fits a bivariate ecdf to the specified pair of variables and then evaluates the ecdf at the same points.
#'
#' @details Assumes u_ref and v_ref specify pairs of points in the correct order.
#' 
#' @param u_ref NumericVector reference points in first dimension
#' @param v_ref NumericVector reference points in second dimension
#'
#' @return NumericVector of estimated quantiles of specified pairs
#' 
#' @export
#' @author Tom Willis
bivariate_ecdf_par_cpp <- function(u_ref, v_ref) {
    .Call(`_pidProjCode_bivariate_ecdf_par_cpp`, u_ref, v_ref)
}

#' @title Bivariate empirical cdf using novel divide-and-conquer algorithm
#'
#' 
#' @param u_ref NumericVector reference points in first dimension
#' @param v_ref NumericVector reference points in second dimension
#'
#' @return NumericVector of estimated quantiles of specified pairs
#' 
#' @export
#' @author Tom Willis
bivariate_ecdf_lw_cpp <- function(u_ref, v_ref) {
    .Call(`_pidProjCode_bivariate_ecdf_lw_cpp`, u_ref, v_ref)
}

